### ISSUE TITLE
新功能：支持图片下载重试

### ISSUE THREAD

**Issue by whyNot-nine** [JoyerLiu/mirai-plugin-midjourney#8]
1.经常报图片下载错误 code500，但实际网址图片生成顺利 ，建议加一个重试
2.change -u  请求错误307

**Comment by EnchantedAI** [comment]
307貌似是图片下载错误就报，希望下载加个重试吧

**Comment by JoyerLiu** [comment]
已修复问题，如果大佬还在使用麻烦帮忙测试一下，我现在的本地环境没法测试，所以发布了预先版本😂
[release alpha 0.1.6](https://github.com/JoyerLiu/mirai-plugin-midjourney/releases/tag/V0.1.6_alpha)

**Comment by JoyerLiu** [comment]
功能已测试完毕，已上线alpha的正式版本
